# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-17 16:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='College',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('college_name', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('tier', models.IntegerField(choices=[(1, 'first'), (2, 'second'), (3, 'third'), (4, 'other')], default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annualFee', models.IntegerField()),
                ('OfficialSite', models.CharField(max_length=1000)),
                ('Name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='colleges.College')),
            ],
        ),
    ]
