# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-22 15:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('colleges', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='details',
            old_name='Name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='details',
            old_name='OfficialSite',
            new_name='officialSite',
        ),
    ]
